POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "bestBlog",
    "author": "anonym",
    "url": "somewhere",
    "likes": 0,
    "user": "6847e10a39743033c18c6287"
}