POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpIiwiaWQiOiI2ODQ3ZTEwYTM5NzQzMDMzYzE4YzYyODciLCJpYXQiOjE3NDk2NDAwODR9.6PKUpCNLCghc-VKHnk_AsMvQCUxOw8_dE6w2TCTuHUc

{
    "title": "blogi2",
    "author": "matti",
    "url": "internet2",
    "likes": 2,
    "user": "6847e10a39743033c18c6287"
}